# Generated by Django 4.1.2 on 2023-04-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesssession',
            name='strength',
            field=models.IntegerField(),
        ),
    ]
